//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public long postId { get; set; }
        public string message { get; set; }
        public string messagekey { get; set; }
        public string digitalSignature { get; set; }
        public long signer { get; set; }
        public byte[] timestamp { get; set; }
        public int keyVersion { get; set; }
        public long groupId { get; set; }
        public long originalPostId { get; set; }
        public string postType { get; set; }
    }
}
